# Generated by Django 4.2.6 on 2023-10-11 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="answer_text",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question_text",
            new_name="text",
        ),
    ]
