# Generated by Django 4.2.6 on 2023-10-11 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_answer_text_question_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="creation_date",
            new_name="created",
        ),
    ]
