# Generated by Django 4.2.6 on 2023-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_creation_date_question_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateTimeField(),
        ),
    ]
